### ISSUE TITLE
gallium

### ISSUE THREAD

**Issue by joeblew99** [gernest/qlql#1]
gallium is a replacement for electron. Its golang based, and so removes the need for Nodejs etc.

it currently ONLY works on OSX, but is planned to work on windows and linux.

SO just putting this here for now so you knwo about gallium.

**Comment by gernest** [comment]
@joeblew99 sorry! I don't get this!

Is this a feature request? This project is for electron! Any PR is welcome though!

I don't know anything about gallium and I suck big time at UI/UX and front end so it really doesn't ring a bell!

**Comment by joeblew99** [comment]
:)

Gallium is an alternative to Electron.
Its does the same thing as Electron, but is based on golang.
So, with gallium, you dont ned any node js and have much more control

Hope that make its advantages clear.
i used to use Electron but changed to Gallium and its been great

**Comment by gernest** [comment]
@joeblew99 you can submit a PR that uses gallum! I will merge it!

**Comment by joeblew99** [comment]
i will leave it for now.
i like gallium, but i also found this one.
still trying out to see one works best.
So, i will leave the link here for future reference.

right now this look best:
https://github.com/murlokswarm/app#getting-started
