### ISSUE TITLE
vecty fork

### ISSUE THREAD

**Issue by joeblew99** [gernest/qlql#2]
Can you fork the path too ?

https://github.com/gernest/qlql/blob/master/app/main.go#L5

Basically change to use your github repo not the common one.
this makes it much easier to run your version of vecty and theirs.

**Comment by gernest** [comment]
That make sense, but I'm onto other things now. A PR will be highly appreciated!

My fork is here https://github.com/gernest/vecty

**Comment by joeblew99** [comment]
for now i just did a git clone of your vecty to try this out.
works well.

Will close for now. We can revisit it later if need be.
